In [1]:
from nltk.tokenize import word_tokenize
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tfidf = TfidfVectorizer()
sentence1 = 'It is a good practice for us.'
sentence2 = 'It was also good to know about it.'

In [25]:
x_new = tfidf.fit_transform([sentence1, sentence2])
x_new.toarray()

array([[0.        , 0.        , 0.44665616, 0.31779954, 0.44665616,
        0.31779954, 0.        , 0.44665616, 0.        , 0.44665616,
        0.        ],
       [0.36439074, 0.36439074, 0.        , 0.25926702, 0.        ,
        0.51853403, 0.36439074, 0.        , 0.36439074, 0.        ,
        0.36439074]])

In [26]:
df_tfidf = pd.DataFrame(data=x_new.toarray(), columns=tfidf.get_feature_names_out())
df_tfidf

,about,also,for,good,is,it,know,practice,to,us,was
0,0.000000,0.000000,0.446656,0.317800,0.446656,0.317800,0.000000,0.446656,0.000000,0.446656,0.000000
1,0.364391,0.364391,0.000000,0.259267,0.000000,0.518534,0.364391,0.000000,0.364391,0.000000,0.364391

In [36]:
# Opening a file with multiple sentences and tf-idf on it
tf_idf_vect = TfidfVectorizer()
with open('doc1.txt', 'r') as f:
    tf_idf_array = tf_idf_vect.fit_transform(f.readlines()).toarray() # fit_transform accepts a list of sentences and then the sparse matrix is converted to numpy array
tf_idf_array

array([[0.        , 0.        , 0.        , 0.3706774 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.45203772, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.45203772, 0.        , 0.3706774 , 0.45203772,
        0.        , 0.20065925, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.26817551],
       [0.36396129, 0.36396129, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.36396129, 0.        ,
        0.        , 0.        , 0.36396129, 0.36396129, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.36396129, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.16156218, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.36396129, 0.        ,
        0.21592337],
       [0.        , 0.        , 0.40752929, 0.        , 0.        ,
        0.40752929, 0.        , 0.        , 0.        , 0.        ,
        0.33417985, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33417985, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.18090199, 0.40752929, 0.        , 0.28213759,
        0.        , 0.        , 0.        , 0.        , 0.40752929,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40170535, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.40170535,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.40170535, 0.17831674, 0.        , 0.40170535, 0.        ,
        0.40170535, 0.40170535, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33901767, 0.        , 0.33901767, 0.        ,
        0.        , 0.33901767, 0.        , 0.        , 0.33901767,
        0.33901767, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.33901767, 0.        ,
        0.        , 0.        , 0.        , 0.27799934, 0.        ,
        0.        , 0.15048972, 0.        , 0.        , 0.23470614,
        0.        , 0.        , 0.33901767, 0.        , 0.        ,
        0.20112533],
       [0.        , 0.        , 0.        , 0.24198311, 0.29509621,
        0.        , 0.        , 0.        , 0.        , 0.29509621,
        0.24198311, 0.        , 0.29509621, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.29509621, 0.24198311, 0.29509621, 0.        , 0.29509621,
        0.        , 0.        , 0.29509621, 0.        , 0.        ,
        0.        , 0.13099301, 0.        , 0.        , 0.40859754,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.17506853]])

In [37]:
df_new = pd.DataFrame(data=tf_idf_array, columns=tf_idf_vect.get_feature_names_out())
df_new

,30,at,before,can,customer,deadline,do,does,door,earlier,...,the,this,time,to,tonight,what,when,will,work,you
0,0.000000,0.000000,0.000000,0.370677,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.200659,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.268176
1,0.363961,0.363961,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.161562,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.363961,0.000000,0.215923
2,0.000000,0.000000,0.407529,0.000000,0.000000,0.407529,0.000000,0.000000,0.000000,0.000000,...,0.180902,0.407529,0.000000,0.282138,0.000000,0.000000,0.000000,0.000000,0.407529,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.401705,0.000000,0.000000,...,0.178317,0.000000,0.401705,0.000000,0.401705,0.401705,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.339018,0.000000,0.339018,0.000000,...,0.150490,0.000000,0.000000,0.234706,0.000000,0.000000,0.339018,0.000000,0.000000,0.201125
5,0.000000,0.000000,0.000000,0.241983,0.295096,0.000000,0.000000,0.000000,0.000000,0.295096,...,0.130993,0.000000,0.000000,0.408598,0.000000,0.000000,0.000000,0.000000,0.000000,0.175069